# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['AngleX', 'AngleY', 'LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Frog', 'StandInit', 'HeadBack', 'Belly', 'Right', 'Back', 'Left', 'Stand', 'Sit', 'Knee', 'Crouch']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    return data, target

In [7]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE

for i in range(len(classes)):
    all_data += load_pose_data(i)[0]
    all_target += load_pose_data(i)[1]
    

print 'total number of data', len(all_data)

total number of data 200


In [16]:
# shuffule data
permutation = np.random.permutation(len(all_data))
print(permutation)
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]
print(training_data)

[143  47 177 118  68  17 100  48 101 174 148  87  80  54 127 155  44  77
 197 171  57  74 142 134 141   4 136 120   5  40 121  28 107  95  29  55
 159  96   2 175   7  20 116 132  22  82 104  86 108  89  93  50  53 146
   1 193 106  78 139 115  43 180  34 135 145  12 152  61 160 166  51 158
   9  67  33 154 137 122  37  79  85  59 199 196 188  36  25  14 112 113
  91 183  65  23 103  62   8 176   0 157  10 172  69 169  75 133  70 102
 198 150 110 111  42  99 168  13 163 140 126  41 173  84  63  39 153 184
 114  58 164  45 185 151 195 162 117 182 105  49 119  76 167 187  52  11
 156  32 130 109 181 192  94  15  60  26  97 161 128 123  66  35 189 191
  64 178  56  73  83 124  24 147  90  46  21  31 144  18 186  98  19  92
  81 125 179  38   3   6 149  27 170 131 194  88 190 129 165  16  72  30
  71 138]
[143  47 177 118  68  17 100  48 101 174 148  87  80  54 127 155  44  77
 197 171  57  74 142 134 141   4 136 120   5  40 121  28 107  95  29  55
 159  96   2 175   7  20 116 132  22  82 

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [9]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [18]:
# YOUR CODE HERE

print(all_data[1])
print all_target[1]

cut_data = []
cut_target = []

#70% of the data
for i in range(n_training_data):
    cut_data.append(all_data[training_data[i]])
    cut_target.append(all_target[training_data[i]])

#learn
clf.fit(cut_data,cut_target)

[-0.40953612327575684, -0.19631004333496094, -1.5815120935440063, 2.136820077896118, -0.40953612327575684, 0.2853660583496094, -1.6613640785217285, 2.13997220993042, -0.03490638732910156, 0.9913468360900879]
0


SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### predicting

In [58]:
clf.predict(all_data[-1]), all_target[-1]

(array([10]), 10)

In [22]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [25]:
expected = []
predicted = []
# YOUR CODE HERE

predicted = clf.predict(cut_data)
expected = cut_target
evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       1.00      1.00      1.00        34
          2       1.00      1.00      1.00         7
          3       1.00      1.00      1.00         7
          4       1.00      1.00      1.00         7
          5       1.00      1.00      1.00         7
          6       1.00      1.00      1.00        19
          7       1.00      1.00      1.00         4
          8       1.00      1.00      1.00        21
          9       1.00      1.00      1.00         7
         10       1.00      1.00      1.00        19

avg / total       1.00      1.00      1.00       140


Confusion matrix:
[[ 8  0  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0]
 [ 0  0  0  0  0  0 19  0  0  0  0]
 [ 0  0  0  0 

## 4. Evaluate on the test data

In [28]:
expected = []
predicted = []

test_data = []

for i in range(len(all_data)):
    if i not in training_data:
        test_data.append(all_data[i])
        expected.append(all_target[i])
# YOUR CODE HERE

predicted = clf.predict(test_data)

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         2
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00         3
          3       1.00      1.00      1.00         3
          4       1.00      0.75      0.86         4
          5       1.00      1.00      1.00         3
          6       1.00      1.00      1.00         1
          7       1.00      1.00      1.00         7
          8       1.00      1.00      1.00         5
          9       1.00      1.00      1.00         3
         10       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        60


Confusion matrix:
[[ 2  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  1]
 [ 0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [29]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [30]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1]), all_target[-1]

/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


(array([10]), 10)